version: '2'

networks:
    manylinux_network:

services:
    pypi:
        image: pypiserver/pypiserver
        ports:
            - 8080:8080
        volumes:
            - ./packages:/data/packages
            - ./etc/pypiserver/.htpasswd:/data/.htpasswd
        command: -P .htpasswd --overwrite packages
        networks:
            - manylinux_network
    web-docker:
        image: web-docker
        build: web
        ports:
            - 5000:5000
        env_file: 
            - .env
        depends_on: 
            - redis
            - mysql
        volumes:
            - ./web:/opt/app
            - /var/run/docker.sock:/var/run/docker.sock
        command: flask run --host=0.0.0.0
        networks:
            - manylinux_network
    redis:
        image: redis
        ports:
            - 6379:6379
        networks:
            - manylinux_network
    celery:
        image: web-docker
        env_file: 
            - .env
        depends_on: 
            - redis
            - mysql
        volumes:
            - ./web:/opt/app
            - /var/run/docker.sock:/var/run/docker.sock
        command: celery -A server.celery worker --loglevel=info
        networks:
            - manylinux_network
    mysql:
        image: mariadb:10.1
        env_file: 
            - .env
        volumes:
            - ./data/mysql:/var/lib/mysql
        env_file: .env
        networks:
            - manylinux_network
